[package]
name = "chasqui-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.7"
chrono = "0.4.42"
derive_more = { version = "2.1.0", features = ["display"] }
dotenv = "0.15.0"
markdown = "1.0.0"
serde = "1.0.228"
serde_json = "1.0.145"
sqlx = { version = "=0.8.6", features = [
  "runtime-tokio",
  "tls-native-tls",
  "sqlite",
  "chrono",
  "macros",
] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
walkdir = "2.5.0"
